apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JKBGIT1/brightpick-interview-task.git
    targetRevision: feat/basic-security-hardening
    path: k8s/web-apps/nginx-web-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-web-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
