apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: linkerd-edge
  namespace: linkerd
spec:
  interval: 1h
  url: https://helm.linkerd.io/edge
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 10m
  chart:
    spec:
      chart: linkerd-crds
      version: 2026.1.4
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
        namespace: linkerd
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  dependsOn:
    - name: linkerd-crds
  interval: 10m
  chart:
    spec:
      chart: linkerd-control-plane
      version: 2026.1.4
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
        namespace: linkerd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: tls.key
      targetPath: identity.issuer.tls.keyPEM
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd
spec:
  dependsOn:
    - name: linkerd-control-plane
  interval: 10m
  chart:
    spec:
      chart: linkerd-viz
      version: 2026.1.4
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
        namespace: linkerd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
