apiVersion: v1
kind: Namespace
metadata:
  name: nginx-web-app
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web-app
  name: nginx-web-app
  namespace: nginx-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - image: nginx:stable-alpine3.23-slim
        name: nginx
        resources: 
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-app
  namespace: nginx-web-app
  labels:
    app: nginx-web-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx-web-app
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-web-app-issuer
  namespace: nginx-web-app
spec:
  selfSigned: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-web-app-gateway
  namespace: nginx-web-app
  annotations:
    cert-manager.io/issuer: nginx-web-app-issuer
spec:
  gatewayClassName: traefik
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: websecure
    port: 8443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: nginx-web-app-tls
  - allowedRoutes:
      namespaces:
        from: Same
    name: web
    port: 8000
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-web-app
  namespace: nginx-web-app
spec:
  parentRefs:
    - name: nginx-web-app-gateway
      namespace: nginx-web-app
  hostnames:
    - brightpick.app.test
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-web-app
          port: 80
