- op: replace
  path: /data/OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT
  value: "1"
- op: replace
  path: /data/OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED
  value: "false"
- op: replace
  path: /data/OPERATOR_RBAC_ASSESSMENT_SCANNER_ENABLED
  value: "false"
- op: replace
  path: /data/OPERATOR_INFRA_ASSESSMENT_SCANNER_ENABLED
  value: "false"
- op: replace
  path: /data/OPERATOR_EXPOSED_SECRET_SCANNER_ENABLED
  value: "false"
- op: replace
  path: /data/OPERATOR_SBOM_GENERATION_ENABLED
  value: "false"
